version: "3"
services:
  akvo-data-science-auth:
    environment:
     - AUTH_USER_PASSWORD=${AUTH_USER_PASSWORD}
     - AUTH_USER_EMAIL=${AUTH_USER_EMAIL}
     - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
     - AUTH_CLIENT_PASSWORD=${AUTH_CLIENT_PASSWORD}
     - AUTH_ISSUER=${AUTH_ISSUER}
    build: ./../../support/auth/
  api:
    environment:
     - LUMEN_DOMAIN=${LUMEN_DOMAIN}
    build: .
    volumes:
     - ./data:/data
     - .:/app
    ports:
     - "7001:8000"
