apiVersion: apps/v1
kind: Deployment
metadata:
  name: akvo-data-science-${project_folder}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: akvo-data-science-${project_folder}
  template:
    metadata:
      labels:
        run: akvo-data-science-${project_folder}
        code-version: ${TRAVIS_COMMIT}
    spec:
      containers:
      - name: akvo-data-science-${project_folder}
        image: eu.gcr.io/akvo-lumen/akvo-data-science-${project_folder}:${TRAVIS_COMMIT}
        ports:
        - containerPort: 8000
        env:
        - name: K8S_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: akvo
              key: environment
---
apiVersion: v1
kind: Service
metadata:
  name: akvo-data-science-${project_folder}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    run: akvo-data-science-${project_folder}
