apiVersion: apps/v1
kind: Deployment
metadata:
  name: akvo-data-science-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      run: akvo-data-science-auth
  template:
    metadata:
      labels:
        run: data-science-services
        code-version: ${TRAVIS_COMMIT}
    spec:
      containers:
      - name: akvo-data-science-auth
        image: eu.gcr.io/akvo-lumen/akvo-data-science-auth:${TRAVIS_COMMIT}
        ports:
        - containerPort: 8000
        env:
        - name: AUTH_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: akvo
              key: auth.public.client.id
        - name: AUTH_CLIENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-science
              key: auth0.client_secret
        - name: AUTH_USER_EMAIL
          valueFrom:
            secretKeyRef:
              name: data-science
              key: auth0.user_email
        - name: AUTH_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-science
              key: auth0.user_password
        - name: AUTH_ISSUER
          valueFrom:
            configMapKeyRef:
              name: akvo
              key: auth.url
---
apiVersion: v1
kind: Service
metadata:
  name: akvo-data-science-auth
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    run: akvo-data-science-auth
